services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${TIRUM_RADARR_CONFIG_FOLDER}:/config
      - ${TIRUM_RADARR_MOVIES_FOLDER}:/movies
      - ${TIRUM_TORRENT_DOWNLOAD_FOLDER}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=adminadmin
    volumes:
      - ${TIRUM_TORRENT_CONFIG_FOLDER}:/config
      - ${TIRUM_TORRENT_DOWNLOAD_FOLDER}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  
  # configurator:
  #   image: docker pull ghcr.io/astral-sh/uv:0.8-alpine3.22

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${TIRUM_PROWLARR_CONFIG_FOLDER}:/config
    ports:
      - 9696:9696
    restart: unless-stopped
